### ISSUE TITLE
Download button on top of rating buttons.

### ISSUE THREAD

**Issue by Briareos17** [lethak/digitally_imported_userscript#24]
I find out that download button rendering above thumbs buttons and prevents from clicking on thumbs up/down, fix this issue pls, I really like to leave my feedback about tracks.

**Comment by lethak** [comment]
Problem confirmed on windows/chrome
but not occurring on linux/chrome _75.0.3770.80 (Official Build) (64-bit)_

Temporary workaround is to play this code in the browser  console (F12) to remove the DL button

```javascript
setInterval(function() { $('.diu-buttons .dlAction').parent().remove() }, 1800)
```
you can add this code at the very end of the tempermonkey script (edit and save) in order to not bother doing it manually; plus it will be removed on the next version bump.

I'll fix it permanently on the next release.

**Comment by lethak** [comment]
I edited my previous comment to include 'setInterval' in the workaround so you only have to use it once per page load and not after each track change.

**Comment by lethak** [comment]
The latest v2019.8.2 version should have the problem fixed, closing
