### ISSUE TITLE
autofill track name when downloading.

### ISSUE THREAD

**Issue by Briareos17** [lethak/digitally_imported_userscript#33]
Every time I want to download track, I need to copyppaste artist and track name from player to download windo, is there any way to make this process automated?

**Comment by lethak** [comment]
Hi,

Technically it would be possible if I were using the "[@grant GM_download](https://www.tampermonkey.net/documentation.php#GM_download)" userscript directive

I specifically don't want to use any grant directive for now since i'd like the script to be as neutral as possible.

Another possibility remains with 

```html
<a download="bar.txt" href="foo.txt">lorem ipsum</a>​​​​​​​​​​​​​​​​​​​​​​​​​​​
```

I'll give it a try for a next version, but its not compatible with most older browsers.

**Comment by lethak** [comment]
Regarding the HTML A HREF/DOWNLOAD tag,  apparently "Chrome 65+ and Firefox only support same-origin download links." sooo, since they uses an alternative domain as CDN (content.audioaddict.com), this wont work.

I'll think on adding the grant directive.

**Comment by Briareos17** [comment]
This would be awesome!

**Comment by Briareos17** [comment]
You are awesome!
