### ISSUE TITLE
Play Audio on Same page

### ISSUE THREAD

**Issue by Nzzyme** [lethak/digitally_imported_userscript#35]
Hi there,

Just installed your script and was amazed by the features. A big thank you for this awesome script.

I am a regular listener of zenradio.com and wanted to check with you if it is possible to click on the play button of a channel and the track starts playing on the same page at the bottom? That is, visit zenradio.com or other audio addict sites like radiotunes.com and then on the homepage, click on the play button of any channel and the track should begin playing on the same page at the bottom (just like it does on di.fm)? Can you please implement this?

**Comment by lethak** [comment]
Hi and thanks!

Non-di sites are built differently and while some success may be achieved in this direction through the script, I am not confident this would be fully seamlessly integrated. In fact this specific "problem" is preventing the use of some features on those sites. The script would have to build its own player bar in order to do that, which is a monumental task to handle.

I am not closing this issue since its a valid enhancement request, but I am not confident it will arrive anytime soon.

**Comment by Nzzyme** [comment]
> Hi and thanks!
> 
> Non-di sites are built differently and while some success may be achieved in this direction through the script, I am not confident this would be fully seamlessly integrated. In fact this specific "problem" is preventing the use of some features on those sites. The script would have to build its own player bar in order to do that, which is a monumental task to handle.
> 
> I am not closing this issue since its a valid enhancement request, but I am not confident it will arrive anytime soon.

I understand but if it helps, I requested someone to create a similar music player through a script for the bandcamp site and it was built so I am thinking you can refer that code and build something on the same lines?

Just incase, I am providing you with the link: https://github.com/cvzi/Bandcamp-script-deluxe-edition

**Comment by lethak** [comment]
Good news, the ajax navigation and audio player is now operational on non-DI sites as well, natively.
With script features handled since [v2023.4.92](https://github.com/lethak/LTKDIFMU-userscript/tree/v2023.4.92)
